[package]
name = "minecraft"
version = "5.0.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "systemd_minecraft"
path = "src/lib.rs"

[[bin]]
name = "minecraft"
path = "src/main.rs"
doc = false

[dependencies]
clap = "2"
crossbeam-channel = "*"
derive_more = "0.99"
itertools = "0.8"
rcon = "0.1"
serde_json = "1"
signal-hook = "0.1"

[dependencies.serde]
version = "1"
features = ["derive"]
